FROM hansode/centos-6-x86_64

RUN yum install --disablerepo=updates -y git make sudo yum-utils tar rpm-build rpmdevtools
RUN yum install --disablerepo=updates -y http://ftp.riken.jp/Linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm
